// TOGGLE MODAL
export const TOGGLE_MODAL_ACTION = 'TOGGLE_MODAL_ACTION';

//USER REGISTRATION
export const USER_REGISTRATION_ACTION = 'USER_REGISTRATION_ACTION';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';

//USER LOGIN
export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//ALL REPORTED CASES
export const ALL_REPORTED_CASES_ACTION = 'ALL_REPORTED_CASES_ACTION';
export const ALL_REPORTED_CASES_SUCCESS = 'ALL_REPORTED_CASES_SUCCESS';
export const ALL_REPORTED_CASES_FAIL = 'ALL_REPORTED_CASES_FAIL';

//RESET PASSWORD
export const RESET_PASSWORD_ACTION = 'RESET_PASSWORD_ACTION';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
